<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.matheclipse</groupId>
    <artifactId>matheclipse</artifactId>
    <version>1.0.0-android-SNAPSHOT</version>
    <packaging>jar</packaging>

    <description>Symja Java Symbolic Math library.</description>
    <url>https://github.com/axkr/symja_android_library.git</url>

    <licenses>
        <license>
            <name>GNU General Public License, Version 3</name>
            <url>http://www.gnu.org/licenses/gpl-3.0.html</url>
            <distribution>repo</distribution>
            <comments>A free, copyleft license for software and other kinds of works</comments>
        </license>
        <license>
            <name>GNU Lesser General Public License, Version 3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0.html</url>
            <distribution>repo</distribution>
            <comments>A free, copyleft license for software and other kinds of works</comments>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>axelclk</id>
            <name>Axel Kramer</name>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>com.atlassian.commonmark</groupId>
            <artifactId>commonmark</artifactId>
            <version>0.15.0</version>
        </dependency>
        <dependency>
            <groupId>com.atlassian.commonmark</groupId>
            <artifactId>commonmark-ext-gfm-tables</artifactId>
            <version>0.15.0</version>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.13.1</version>
            <scope>test</scope>
        </dependency>
         <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>

                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>../symja_android_library/matheclipse-core/src/main/java</source>
                                <source>../symja_android_library/matheclipse-frontend/src/main/java</source>
                                <source>../symja_android_library/matheclipse-api/src/main/java</source>
                                <source>../symja_android_library/matheclipse-io/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>

                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>../symja_android_library/matheclipse-core/src/test/java/</source>
                                <source>../symja_android_library/matheclipse-api/src/test/java/</source>
                                <source>../symja_android_library/matheclipse-io/src/test/java/</source>
                                <source>../symja_android_library/tools/src/main/java/</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
