package source;

import junit.framework.TestCase;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 * Created by Duy on 2/25/2018.
 */

public class Lab4IntSourceGetter extends TestCase {
    private static final String SOURCE_PREFIX = "http://www.lab4inf.fh-muenster.de/lab4inf/Lab4Math/xref/";
    private static final String ALL_CLASSES_FRAME = "http://www.lab4inf.fh-muenster.de/lab4inf/Lab4Math/xref/allclasses-frame.html";
    private final File javaDir = new File("D:\\github\\symja_android_library_contri\\symja_android_library\\matheclipse-core\\src\\main\\java");
    private volatile int threadCount = 0;

    public void testGetSource() throws IOException, InterruptedException {
        Document document = Jsoup.connect(ALL_CLASSES_FRAME).get();
        Elements allClasses = document.body().getElementsByTag("li");
        for (Element aClass : allClasses) {
            final String link = aClass.getElementsByTag("a").get(0).attr("href");
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        threadCount++;
                        downloadAndModifiedSource(link);
                        threadCount--;
                    } catch (IOException e) {
                        e.printStackTrace();
                        fail(e.getMessage());
                    }
                }
            }).start();
        }
        Thread.sleep(1000);
        while (threadCount > 0) {
            Thread.sleep(100);
        }
    }

    public void test1() throws IOException {
        downloadAndModifiedSource("de/lab4inf/math/Solver.html");
    }

    public void test2() throws IOException {
        downloadAndModifiedSource("de/lab4inf/math/differentiation/Differentiator");
    }

    private void downloadAndModifiedSource(final String path) throws IOException {
        System.out.println("link = " + path);
        String url = SOURCE_PREFIX + path;
        Document document = Jsoup.connect(url).get();
        String rawSource = document.body().text();

        rawSource = rawSource.replace("View Javadoc", "");
        rawSource = rawSource.replace("This page was automatically generated by Maven", "");
        rawSource = rawSource.replaceAll("[\r\n]+[0-9]+", "\n");

        File file = new File(javaDir, path.replace(".html", ".java"));
        file.getParentFile().mkdirs();
        file.createNewFile();
        FileOutputStream fos = new FileOutputStream(file);
        fos.write(rawSource.getBytes());
        fos.flush();
        fos.close();
    }


}
