package org.matheclipse.core.expression;

import org.matheclipse.core.interfaces.IBuiltInSymbol;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;
import org.matheclipse.parser.client.FEConfig;
import org.matheclipse.parser.trie.Tries;

import java.util.Locale;
import java.util.Map;

import it.unimi.dsi.fastutil.objects.Object2ShortOpenHashMap;

/**
 * Factory for creating Symja built-in symbols (interface {@link IBuiltInSymbol}). The built-in symbols are generated
 * with the tools class <code>BuiltinGenerator</code>.
 */
public class S extends F {
//  public static final ISymbol x = F.x;
//
//  public static final IBuiltInSymbol Undefined = F.Undefined;
//  public static final IBuiltInSymbol Derivative = F.Derivative;
//  public static final IBuiltInSymbol D = F.D;
//  public static final IBuiltInSymbol Pattern = F.Pattern;
//  public static final IBuiltInSymbol If = F.If;
//  public static final IBuiltInSymbol Nothing = F.Nothing;
//  public static final IBuiltInSymbol FactorTerms = F.FactorTerms;
//  public static final IBuiltInSymbol Power = F.Power;
//  public static final IBuiltInSymbol GoldenAngle = F.GoldenAngle;
//  public static final IBuiltInSymbol GoldenRatio = F.GoldenRatio;
//  public static final IBuiltInSymbol Degree = F.Degree;
//  public static final IBuiltInSymbol ComplexityFunction = F.ComplexityFunction;
//  public static final IBuiltInSymbol Root = F.Root;
//  public static final IBuiltInSymbol GCD = F.GCD;
//  public static final IBuiltInSymbol Distribute = F.Distribute;
//  public static final IBuiltInSymbol Trig = F.Trig;
//  public static final IBuiltInSymbol Apply = F.Apply;
//  public static final IBuiltInSymbol Transpose = F.Transpose;
//  public static final IBuiltInSymbol Denominator = F.Denominator;
//  public static final IBuiltInSymbol Numerator = F.Numerator;
//  public static final IBuiltInSymbol LaguerreL = F.LaguerreL;
//  public static final IBuiltInSymbol Or = F.Or;
//  public static final IBuiltInSymbol Factor = F.Factor;
//  public static final IBuiltInSymbol JSFormData = F.JSFormData;
//  public static final IBuiltInSymbol Modulus = F.Modulus;
//  public static final IBuiltInSymbol Exponent = F.Exponent;
//  public static final IBuiltInSymbol Real = F.Real;
//  public static final IBuiltInSymbol Booleans = F.Booleans;
//  public static final IBuiltInSymbol FindRoot = F.FindRoot;
//  public static final IBuiltInSymbol Integers = F.Integers;
//  public static final IBuiltInSymbol BesselK = F.BesselK;
//  public static final IBuiltInSymbol Solve = F.Solve;
//  public static final IBuiltInSymbol Simplify = F.Simplify;
//  public static final IBuiltInSymbol Complexes = F.Complexes;
//  public static final IBuiltInSymbol Reals = F.Reals;
//  public static final IBuiltInSymbol ReplaceRepeated = F.ReplaceRepeated;
//  public static final IBuiltInSymbol Take = F.Take;
//  public static final IBuiltInSymbol Append = F.Append;
//  public static final IBuiltInSymbol Insert = F.Insert;
//  public static final IBuiltInSymbol PrependTo = F.PrependTo;
//  public static final IBuiltInSymbol Prepend = F.Prepend;
//  public static final IBuiltInSymbol Identity = F.Identity;
//  public static final IBuiltInSymbol Drop = F.Drop;
//  public static final IBuiltInSymbol Pi = F.Pi;
//  public static final IBuiltInSymbol Subtract = F.Subtract;
//  public static final IBuiltInSymbol Expand = F.Expand;
//  public static final IBuiltInSymbol Method = F.Method;
//  public static final IBuiltInSymbol Im = F.Im;
//  public static final IBuiltInSymbol Re = F.Re;
//  public static final IBuiltInSymbol Covariance = F.Covariance;
//  public static final IBuiltInSymbol Unequal = F.Unequal;
//  public static final IBuiltInSymbol Greater = F.Greater;
//  public static final IBuiltInSymbol GreaterEqual = F.GreaterEqual;
//  public static final IBuiltInSymbol Less = F.Less;
//  public static final IBuiltInSymbol LessEqual = F.LessEqual;
//  public static final IBuiltInSymbol Max = F.Max;
//  public static final IBuiltInSymbol Min = F.Min;
//  public static final IBuiltInSymbol And = F.And;
//  public static final IBuiltInSymbol Nor = F.Nor;
//  public static final IBuiltInSymbol Nand = F.Nand;
//  public static final IBuiltInSymbol Inequality = F.Inequality;
//  public static final IBuiltInSymbol Equivalent = F.Equivalent;
//  public static final IBuiltInSymbol Xor = F.Xor;
//  public static final IBuiltInSymbol Implies = F.Implies;
//  public static final IBuiltInSymbol Literal = F.Literal;
//  public static final IBuiltInSymbol Integrate = F.Integrate;
//  public static final IBuiltInSymbol Product = F.Product;
//  public static final IBuiltInSymbol Module = F.Module;
//  public static final IBuiltInSymbol Together = F.Together;
//  public static final IBuiltInSymbol PseudoInverse = F.PseudoInverse;
//  public static final IBuiltInSymbol LinearSolveFunction = F.LinearSolveFunction;
//  public static final IBuiltInSymbol Inverse = F.Inverse;
//  public static final IBuiltInSymbol Dimensions = F.Dimensions;
//  public static final IBuiltInSymbol Det = F.Det;
//  public static final IBuiltInSymbol Eigenvectors = F.Eigenvectors;
//  public static final IBuiltInSymbol AllowedHeads = F.AllowedHeads;
//  public static final IBuiltInSymbol ZeroTest = F.ZeroTest;
//  public static final IBuiltInSymbol $Assumptions = F.$Assumptions;
//  public static final IBuiltInSymbol Assumptions = F.Assumptions;
//  public static final IBuiltInSymbol MaxIterations = F.MaxIterations;
//  public static final IBuiltInSymbol With = F.With;
//  public static final IBuiltInSymbol None = F.None;
//  public static final IBuiltInSymbol GaussianIntegers = F.GaussianIntegers;
//  public static final IBuiltInSymbol Extension = F.Extension;
//  public static final IBuiltInSymbol Hypergeometric2F1 = F.Hypergeometric2F1;
//  public static final IBuiltInSymbol Missing = F.Missing;
//  public static final IBuiltInSymbol PossibleZeroQ = F.PossibleZeroQ;
//  public static final IBuiltInSymbol Dot = F.Dot;
//  public static final IBuiltInSymbol Surd = F.Surd;
//  public static final IBuiltInSymbol ComplexInfinity = F.ComplexInfinity;
//  public static final IBuiltInSymbol Indeterminate = F.Indeterminate;
//  public static final IBuiltInSymbol DirectedInfinity = F.DirectedInfinity;
//  public static final IBuiltInSymbol Infinity = F.Infinity;
//  public static final IBuiltInSymbol Unevaluated = F.Unevaluated;
//  public static final IBuiltInSymbol LongForm = F.LongForm;
//  public static final IBuiltInSymbol GammaRegularized = F.GammaRegularized;
//  public static final IBuiltInSymbol SparseArray = F.SparseArray;
//  public static final IBuiltInSymbol Round = F.Round;
//  public static final IBuiltInSymbol PolyLog = F.PolyLog;
//  public static final IBuiltInSymbol Log = F.Log;
//  public static final IBuiltInSymbol NumericArray = F.NumericArray;
//  public static final IBuiltInSymbol RandomVariate = F.RandomVariate;
//  public static final IBuiltInSymbol NumericArrayQ = F.NumericArrayQ;
//  public static final IBuiltInSymbol NumericArrayType = F.NumericArrayType;
//  public static final IBuiltInSymbol Evaluate = F.Evaluate;
//  public static final IBuiltInSymbol Defer = F.Defer;
//  public static final IBuiltInSymbol Except = F.Except;
//  public static final IBuiltInSymbol Sinh = F.Sinh;
//  public static final IBuiltInSymbol ListLinePlot = F.ListLinePlot;
//  public static final IBuiltInSymbol Sequence = F.Sequence;
//  public static final IBuiltInSymbol ListPlot = F.ListPlot;
//  public static final IBuiltInSymbol Plot = F.Plot;
//  public static final IBuiltInSymbol ParametricPlot = F.ParametricPlot;
//  public static final IBuiltInSymbol PolarPlot = F.PolarPlot;
//  public static final IBuiltInSymbol E = F.E;
//  public static final IBuiltInSymbol Inner = F.Inner;
//  public static final IBuiltInSymbol Times = F.Times;
//  public static final IBuiltInSymbol RegularExpression = F.RegularExpression;
//  public static final IBuiltInSymbol Cos = F.Cos;
//  public static final IBuiltInSymbol Cot = F.Cot;
//  public static final IBuiltInSymbol Csc = F.Csc;
//  public static final IBuiltInSymbol Sec = F.Sec;
//  public static final IBuiltInSymbol ProductLog = F.ProductLog;
//  public static final IBuiltInSymbol Sin = F.Sin;
//  public static final IBuiltInSymbol Tan = F.Tan;
//  public static final IBuiltInSymbol Abs = F.Abs;
//  public static final IBuiltInSymbol Import = F.Import;
//  public static final IBuiltInSymbol Get = F.Get;
//  public static final IBuiltInSymbol Characters = F.Characters;
//  public static final IBuiltInSymbol All = F.All;
//  public static final IBuiltInSymbol UpTo = F.UpTo;
//  public static final IBuiltInSymbol Plus = F.Plus;
//  public static final IBuiltInSymbol AppendTo = F.AppendTo;
//  public static final IBuiltInSymbol $RecursionLimit = F.$RecursionLimit;
//  public static final IBuiltInSymbol Commonest = F.Commonest;
//  public static final IBuiltInSymbol Throw = F.Throw;
//  public static final IBuiltInSymbol $IterationLimit = F.$IterationLimit;
//  public static final IBuiltInSymbol General = F.General;
//  public static final IBuiltInSymbol Key = F.Key;
//  public static final IBuiltInSymbol KeyAbsent = F.KeyAbsent;
//  public static final IBuiltInSymbol Complex = F.Complex;
//  public static final IBuiltInSymbol Integer = F.Integer;
//  public static final IBuiltInSymbol Float = F.Float;
//  public static final IBuiltInSymbol Strict = F.Strict;
//  public static final IBuiltInSymbol Prefix = F.Prefix;
//  public static final IBuiltInSymbol OptimizeExpression = F.OptimizeExpression;
//  public static final IBuiltInSymbol Rational = F.Rational;
//  public static final IBuiltInSymbol Equal = F.Equal;
//  public static final IBuiltInSymbol StyleForm = F.StyleForm;
//  public static final IBuiltInSymbol Echo = F.Echo;
//  public static final IBuiltInSymbol Association = F.Association;
//  public static final IBuiltInSymbol Automatic = F.Automatic;
//  public static final IBuiltInSymbol False = F.False;
//  public static final IBuiltInSymbol Function = F.Function;
//  public static final IBuiltInSymbol In = F.In;
//  public static final IBuiltInSymbol Heads = F.Heads;
//  public static final IBuiltInSymbol Hold = F.Hold;
//  public static final IBuiltInSymbol HoldComplete = F.HoldComplete;
//  public static final IBuiltInSymbol HoldForm = F.HoldForm;
//  public static final IBuiltInSymbol HoldPattern = F.HoldPattern;
//  public static final IBuiltInSymbol Out = F.Out;
//  public static final IBuiltInSymbol Null = F.Null;
//  public static final IBuiltInSymbol Set = F.Set;
//  public static final IBuiltInSymbol SetDelayed = F.SetDelayed;
//  public static final IBuiltInSymbol UpSet = F.UpSet;
//  public static final IBuiltInSymbol UpSetDelayed = F.UpSetDelayed;
//  public static final IBuiltInSymbol Repeated = F.Repeated;
//  public static final IBuiltInSymbol RepeatedNull = F.RepeatedNull;
//  public static final IBuiltInSymbol True = F.True;
//  public static final IBuiltInSymbol List = F.List;
//  public static final IBuiltInSymbol Thread = F.Thread;
//  public static final IBuiltInSymbol MessageName = F.MessageName;
//  public static final IBuiltInSymbol Style = F.Style;
//  public static final IBuiltInSymbol IgnoreCase = F.IgnoreCase;
//  public static final IBuiltInSymbol Part = F.Part;


}
